/*
 * Copyright (c) 2026, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.tools.docs;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

/**
 * Hand-rolled YAML writer for the connection-properties data file
 * consumed by the {@code param-table} Hugo shortcode. The output shape
 * is fixed and narrow (one flat list of dicts with known keys) so we
 * spell it out by hand rather than dragging snakeyaml onto the build
 * classpath.
 *
 * <p>Strings are emitted quoted only when necessary (when they contain
 * characters that YAML treats specially or could be ambiguously parsed
 * as numbers/booleans/nulls). Multi-line descriptions use the
 * {@code >-} folded-and-stripped block scalar.
 */
final class YamlEmitter {

    /** Hard-wrap column for folded description scalars. */
    private static final int WRAP = 78;

    private YamlEmitter() {
        // utility class
    }

    static void writeTo(List<PropertyRecord> records, Path output) throws IOException {
        Files.createDirectories(output.getParent());
        try (Writer w = Files.newBufferedWriter(output, StandardCharsets.UTF_8)) {
            writeHeader(w);
            for (PropertyRecord r : records) {
                writeRecord(r, w);
            }
        }
    }

    private static void writeHeader(Writer w) throws IOException {
        w.write("# Generated by :docs-tools:generateProperties — DO NOT EDIT.\n");
        w.write("# Source of truth: pgjdbc/src/main/java/org/postgresql/PGProperty.java\n");
        w.write("#                  + @PgApi / @PgTags / @PgPropertyType annotations on each value.\n");
        w.write("# Run `./gradlew :docs-tools:generateProperties` to regenerate.\n");
        w.write("\n");
    }

    private static void writeRecord(PropertyRecord r, Writer w) throws IOException {
        w.write("- name:         " + scalar(r.name) + "\n");
        w.write("  type:         " + r.type + "\n");
        w.write("  default:      " + defaultScalar(r.defaultValue) + "\n");
        w.write("  introducedIn: " + scalar(r.introducedIn) + "\n");
        w.write("  status:       " + r.status + "\n");
        if (!r.deprecatedIn.isEmpty()) {
            w.write("  deprecatedIn: " + scalar(r.deprecatedIn) + "\n");
        }
        if (!r.hiddenIn.isEmpty()) {
            w.write("  hiddenIn:     " + scalar(r.hiddenIn) + "\n");
        }
        w.write("  tags:         " + flowList(toLowerCase(r.tags)) + "\n");
        if (r.choices != null && r.choices.length > 0) {
            w.write("  choices:      " + flowList(java.util.Arrays.asList(r.choices)) + "\n");
        }
        if (r.required) {
            w.write("  required:     true\n");
        }
        w.write("  description: " + foldedDescription(r.description) + "\n");
        w.write("\n");
    }

    /* ----- Scalar quoting -------------------------------------------------- */

    /** Quote a string only when it would otherwise be ambiguous to a YAML parser. */
    private static String scalar(String s) {
        if (s == null) {
            return "\"\"";
        }
        if (s.isEmpty()) {
            return "\"\"";
        }
        if (needsQuoting(s)) {
            return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
        }
        return s;
    }

    /** Defaults need special handling: null is rendered as YAML null
     *  (omitted value), the empty string as a quoted empty string. */
    private static String defaultScalar(String d) {
        if (d == null) {
            return "null";
        }
        if (d.isEmpty()) {
            return "\"\"";
        }
        // Always quote numeric/boolean-looking defaults so the consumer
        // treats them as strings consistently with how PGProperty stores them.
        return "\"" + d.replace("\\", "\\\\").replace("\"", "\\\"") + "\"";
    }

    private static boolean needsQuoting(String s) {
        if (s.contains(":") || s.contains("#") || s.contains("\n")
            || s.contains("'") || s.contains("\"") || s.startsWith(" ")
            || s.endsWith(" ")) {
            return true;
        }
        // YAML reserves a set of indicator characters when they appear at
        // the start of a plain scalar: they trigger tags, anchors, aliases,
        // flow collections, block scalars, directives, reserved sigils, or
        // (for `-`) a block-sequence entry. Quote in that case.
        char first = s.charAt(0);
        if (first == '!' || first == '&' || first == '*' || first == '['
            || first == ']' || first == '{' || first == '}' || first == ','
            || first == '|' || first == '>' || first == '%' || first == '@'
            || first == '`' || first == '?' || first == '-') {
            return true;
        }
        if (isYamlReservedScalar(s)) {
            return true;
        }
        return false;
    }

    private static boolean isYamlReservedScalar(String s) {
        String l = s.toLowerCase(Locale.ROOT);
        return l.equals("null") || l.equals("true") || l.equals("false")
            || l.equals("yes")  || l.equals("no")
            || l.equals("on")   || l.equals("off");
    }

    /* ----- List rendering -------------------------------------------------- */

    private static String flowList(List<String> items) {
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < items.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(scalar(items.get(i)));
        }
        sb.append(']');
        return sb.toString();
    }

    private static List<String> toLowerCase(List<String> source) {
        List<String> out = new java.util.ArrayList<>(source.size());
        for (String s : source) {
            out.add(s.toLowerCase(Locale.ROOT));
        }
        return out;
    }

    /* ----- Description block scalar --------------------------------------- */

    /**
     * Render the (possibly long, possibly multi-line) description as a
     * folded-and-stripped block scalar ({@code >-}) so the YAML stays
     * readable in source form and the consumer gets a single-line value.
     */
    private static String foldedDescription(String text) {
        if (text == null || text.isEmpty()) {
            return "\"\"";
        }
        // Normalise whitespace and any embedded newlines into single spaces;
        // the folded scalar will re-wrap them at WRAP for display.
        String normalised = text.replaceAll("\\s+", " ").trim();
        StringBuilder sb = new StringBuilder(">-");
        int col = WRAP + 1;
        for (String word : normalised.split(" ")) {
            int next = col + 1 + word.length();
            if (next > WRAP) {
                sb.append("\n    ");
                col = 4;
                sb.append(word);
                col += word.length();
            } else {
                sb.append(' ').append(word);
                col = next;
            }
        }
        return sb.toString();
    }
}
