/*
 * Copyright (c) 2026, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.tools.docs;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.DumperOptions.FlowStyle;
import org.yaml.snakeyaml.DumperOptions.ScalarStyle;
import org.yaml.snakeyaml.Yaml;
import org.yaml.snakeyaml.nodes.MappingNode;
import org.yaml.snakeyaml.nodes.Node;
import org.yaml.snakeyaml.nodes.NodeTuple;
import org.yaml.snakeyaml.nodes.ScalarNode;
import org.yaml.snakeyaml.nodes.SequenceNode;
import org.yaml.snakeyaml.nodes.Tag;

/**
 * Emits the connection-properties YAML data file consumed by the
 * {@code param-table} Hugo shortcode. The output shape is a flat list
 * of dicts with known keys; we build the snakeyaml node tree directly
 * so that key order, scalar styles (folded descriptions, flow-style
 * tag lists, always-quoted default strings) and the wrap width are all
 * controlled explicitly.
 */
final class YamlEmitter {

    /** Hard-wrap column for folded description scalars. */
    private static final int WRAP = 78;

    private YamlEmitter() {
        // utility class
    }

    static void writeTo(List<PropertyRecord> records, Path output) throws IOException {
        Files.createDirectories(output.getParent());
        try (Writer w = Files.newBufferedWriter(output, StandardCharsets.UTF_8)) {
            writeHeader(w);
            new Yaml(dumperOptions()).serialize(buildSequence(records), w);
        }
    }

    private static DumperOptions dumperOptions() {
        DumperOptions o = new DumperOptions();
        o.setDefaultFlowStyle(FlowStyle.BLOCK);
        o.setIndent(2);
        o.setIndicatorIndent(0);
        o.setWidth(WRAP);
        o.setSplitLines(true);
        o.setLineBreak(DumperOptions.LineBreak.UNIX);
        return o;
    }

    private static void writeHeader(Writer w) throws IOException {
        w.write("# Generated by :docs-tools:generateProperties — DO NOT EDIT.\n");
        w.write("# Source of truth: pgjdbc/src/main/java/org/postgresql/PGProperty.java\n");
        w.write("#                  + @PgApi / @PgTags / @PgPropertyType annotations on each value.\n");
        w.write("# Run `./gradlew :docs-tools:generateProperties` to regenerate.\n");
        w.write("\n");
    }

    private static SequenceNode buildSequence(List<PropertyRecord> records) {
        List<Node> nodes = new ArrayList<>(records.size());
        for (PropertyRecord r : records) {
            nodes.add(buildMapping(r));
        }
        return new SequenceNode(Tag.SEQ, true, nodes, null, null, FlowStyle.BLOCK);
    }

    private static MappingNode buildMapping(PropertyRecord r) {
        List<NodeTuple> tuples = new ArrayList<>();
        tuples.add(tuple("name", str(r.name)));
        tuples.add(tuple("type", str(r.type)));
        tuples.add(tuple("default", defaultNode(r.defaultValue)));
        tuples.add(tuple("introducedIn", str(r.introducedIn)));
        tuples.add(tuple("status", str(r.status)));
        if (!r.deprecatedIn.isEmpty()) {
            tuples.add(tuple("deprecatedIn", str(r.deprecatedIn)));
        }
        if (!r.hiddenIn.isEmpty()) {
            tuples.add(tuple("hiddenIn", str(r.hiddenIn)));
        }
        tuples.add(tuple("tags", flowList(toLowerCase(r.tags))));
        if (r.choices != null && r.choices.length > 0) {
            tuples.add(tuple("choices", flowList(Arrays.asList(r.choices))));
        }
        if (r.required) {
            tuples.add(tuple("required", bool(true)));
        }
        tuples.add(tuple("description", folded(r.description)));
        return new MappingNode(Tag.MAP, true, tuples, null, null, FlowStyle.BLOCK);
    }

    /* ----- Node helpers --------------------------------------------------- */

    private static NodeTuple tuple(String key, Node value) {
        return new NodeTuple(scalar(Tag.STR, key, ScalarStyle.PLAIN), value);
    }

    /**
     * Plain string scalar. snakeyaml's emitter promotes the value to a
     * quoted style on its own when a plain rendering would round-trip as
     * a non-string (e.g. "false", "null", "9.4").
     */
    private static Node str(String s) {
        if (s == null || s.isEmpty()) {
            return scalar(Tag.STR, "", ScalarStyle.DOUBLE_QUOTED);
        }
        return scalar(Tag.STR, s, ScalarStyle.PLAIN);
    }

    /**
     * Defaults need special handling: a {@code null} default is rendered as
     * the YAML {@code null} scalar; every other default is forced to a
     * double-quoted string so numeric/boolean-looking values stay strings
     * on the consumer side (consistent with how PGProperty stores them).
     */
    private static Node defaultNode(String d) {
        if (d == null) {
            return scalar(Tag.NULL, "null", ScalarStyle.PLAIN);
        }
        return scalar(Tag.STR, d, ScalarStyle.DOUBLE_QUOTED);
    }

    private static Node bool(boolean v) {
        return scalar(Tag.BOOL, Boolean.toString(v), ScalarStyle.PLAIN);
    }

    /**
     * Render the (possibly long, possibly multi-line) description as a
     * folded-and-stripped block scalar ({@code >-}). All embedded whitespace
     * is normalised to single spaces so the emitter re-wraps cleanly at
     * {@link #WRAP}.
     */
    private static Node folded(String text) {
        if (text == null || text.isEmpty()) {
            return scalar(Tag.STR, "", ScalarStyle.DOUBLE_QUOTED);
        }
        String normalised = text.replaceAll("\\s+", " ").trim();
        return scalar(Tag.STR, normalised, ScalarStyle.FOLDED);
    }

    private static Node flowList(List<String> items) {
        List<Node> nodes = new ArrayList<>(items.size());
        for (String s : items) {
            nodes.add(str(s));
        }
        return new SequenceNode(Tag.SEQ, true, nodes, null, null, FlowStyle.FLOW);
    }

    private static ScalarNode scalar(Tag tag, String value, ScalarStyle style) {
        return new ScalarNode(tag, value, null, null, style);
    }

    private static List<String> toLowerCase(List<String> source) {
        List<String> out = new ArrayList<>(source.size());
        for (String s : source) {
            out.add(s.toLowerCase(Locale.ROOT));
        }
        return out;
    }
}
