# See https://github.com/release-drafter/release-drafter#configuration-options
name-template: 'v$RESOLVED_VERSION'
tag-template: 'REL$RESOLVED_VERSION'
# Filter previous releases to consider only those with the target matching the current branch
filter-by-commitish: true
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '⬆️ Dependencies'
    collapse-after: 8
    labels:
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
# See https://github.com/release-drafter/release-drafter#autolabeler
autolabeler:
  - label: 'dependencies'
    files:
      - 'gradle-wrapper.properties'
    title:
      - '/^fix\(deps\)/i'
      - '/^chore:\s*bump/i'
  - label: 'chore'
    files:
      - '*gradle*'
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - '/^chore/i'
  - label: documentation
    files:
      - '*.md'
      - 'docs/**'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    title:
      - '/^feat/i'
