codecov:
  notify:
    after_n_builds: 10
    require_ci_to_pass: false
comment:
  layout: header, changes, diff
coverage:
  status:
    patch: false
  range: "60...100"
ignore:
  - "**/translation/message*.java"
