#! /bin/bash -ex

copr_fe_url=https://copr.fedorainfracloud.org/coprs/g/pgjdbc/pgjdbc-travis/build/
copr_be_link=https://copr-be.cloud.fedoraproject.org/results/@pgjdbc/pgjdbc-travis/fedora-rawhide-x86_64/
status_file=copr_build_id

copr_wrapper ()
{
    str="Created builds: "

    copr-cli "$@" 2>&1 | \
    while read line
    do
        case $line in
        "$str"*)
            echo "${line##$str}" > "$status_file"
            ;;
        esac
    done
}

set -o pipefail
cd "$1"
srpmgen
dist=$(date +%Y%m%d_%H%M%S)
TZ=UTC build_local -bs "$2".spec --define "dist .$dist"

copr_wrapper --config "$1"/copr-token build --nowait @pgjdbc/pgjdbc-travis "$2-$3-1.$dist.src.rpm"
copr_build_id=$(cat "$status_file")

concrete_copr_be_link=$copr_be_link$(printf "%08d" "$copr_build_id")-postgresql-jdbc/

: "For build status, logs, etc. have a look at
$copr_fe_url/$copr_build_id/

Note that there might be multiple builds submitted, particularly if there copr
is configured to build for multiple versions of Fedora distribution.  For
concrete build results against latest Fedora version, have a look at:
$concrete_copr_be_link"

exit_cmd=:
while :
do
    status_output=$(copr --config "$1"/copr-token status "$copr_build_id")
    case $status_output in
        succeeded)
            break
            ;;
        failed)
            exit_cmd=false
            break
            ;;
        *)
            : "build $copr_build_id is in \"$status_output\" state"
            ;;
    esac
    sleep 30
done

: getting the build log for rawhide chroot
curl $concrete_copr_be_link/build.log.gz | gunzip || :

$exit_cmd
