import java.time.Duration

plugins {
    id("build-logic.build-params")
    id("com.gradleup.nmcp.aggregation")
    id("com.github.autostyle")
}

nmcpAggregation {
    centralPortal {
        username = providers.environmentVariable("CENTRAL_PORTAL_USERNAME")
        password = providers.environmentVariable("CENTRAL_PORTAL_PASSWORD")
        publishingType = buildParameters.centralPortal.publishingType.name
        validationTimeout = Duration.ofMinutes(buildParameters.centralPortal.validationTimeout.toLong())
    }
}

// build-logic.style (and thus Autostyle) is applied to Java subprojects only, so the files
// under docs/ and .github/ are never checked. This plugin is applied to the root project only,
// so it is the natural place to cover them.
//
// WORKAROUND: string globs do not work — target("**/*.md") matches nothing because
// BaseFormatExtension resolves a String target via Project.files(), which does not expand
// Ant-style globs. Fixed upstream on the autostyle branch fix/string-glob-target; once a release
// with that fix is available, drop the fileTree() wrappers (and the binary/generatedPaths
// excludes below) in favour of string targets such as target("docs/**", ".github/**").
val binaryExtensions = listOf("png", "ico", "woff", "woff2", "jar", "p12", "pk8")
// Autostyle scans the working tree, not the git index, so exclude git-ignored generated or
// vendored trees it would otherwise trip over (Hugo output, npm deps).
val generatedPaths = listOf(
    "docs/public/**",
    "docs/resources/**",
    "docs/.hugo_build.lock",
    ".github/workflows/node_modules/**"
)
autostyle {
    // Markdown only gets a final newline. Trailing whitespace is significant in Markdown,
    // and .editorconfig sets trim_trailing_whitespace = false for *.md.
    format("docsAndGithubMarkdown") {
        target(
            fileTree(rootDir) {
                include("docs/**/*.md", ".github/**/*.md")
                generatedPaths.forEach { exclude(it) }
            }
        )
        endWithNewline()
    }
    // Every other text file under docs/ and .github/: strip trailing whitespace and ensure a
    // final newline, matching the [*] section of .editorconfig.
    format("docsAndGithub") {
        target(
            fileTree(rootDir) {
                include("docs/**", ".github/**")
                exclude("**/*.md")
                binaryExtensions.forEach { exclude("**/*.$it") }
                generatedPaths.forEach { exclude(it) }
                // Generated by npm, keep it byte-for-byte.
                exclude(".github/workflows/package-lock.json")
            }
        )
        trimTrailingWhitespace()
        endWithNewline()
    }
}

// The umbrella style/styleCheck tasks live in build-logic.style (Java subprojects only).
// Register root equivalents so `./gradlew style` / `./gradlew styleCheck` cover docs/ and .github/.
if (!buildParameters.skipAutostyle) {
    tasks.register("style") {
        group = "verification"
        description = "Formats the sources (whitespace, final newline, ...) under docs/ and .github/"
        dependsOn("autostyleApply")
    }
    tasks.register("styleCheck") {
        group = "verification"
        description = "Reports code style violations under docs/ and .github/"
        dependsOn("autostyleCheck")
    }
}
