
= JDBC YugaByteDB Example

Sample JDBC application using the cluster-aware https://github.com/yugabyte/jdbc-yugabytedb[YugabyteDB JDBC driver].

== Usage:

=== 1. Install YugabyteDB

You need to install YugabyteDB on your system. If you have YugabyteDB already installed then check its version.
It should be 2.7.2.0-b0 or above version of YugabyteDB to run these load balancing examples apps.

=== 2. Build the demo examples
Run `mvn package` before starting the `run` script

=== 3. Run this script for a demo
Once you have YugaByteDB installed in your system, then for a demo you just need to run this script.
The script can be run in verbose and/or interactive mode. Check the help of the script to understand
the usage.

The script starts a cluster, demonstrates different flavors of load balancing through java apps.
At the end of the demo it destroys the cluster.

[source, sh]
---
./run.sh [-v] [-i] -D <path/to/yugabyte/installation/>
---
where
 -v is for VERBOSE mode
 -i is for INTERACTIVE mode
 and `<path/to/yugabyte/installation/>` is the path to the directory where yugabyte was installed in step 1.

for example: `./run.sh -v -i -D ~/yugabyte-2.7.2.0/`

This script will first show you a menu, from where you will have to select the option based on which example you want to run among UniformLoadBalance and TopologyAwareLoadBalance.
Then the corresponding script will start running with its java app in background.


