/*
 * Copyright (c) 2026, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.tools.docs

import org.postgresql.tools.docs.YamlEmitter.WRAP
import org.yaml.snakeyaml.DumperOptions
import org.yaml.snakeyaml.DumperOptions.FlowStyle
import org.yaml.snakeyaml.DumperOptions.ScalarStyle
import org.yaml.snakeyaml.Yaml
import org.yaml.snakeyaml.nodes.MappingNode
import org.yaml.snakeyaml.nodes.Node
import org.yaml.snakeyaml.nodes.NodeTuple
import org.yaml.snakeyaml.nodes.ScalarNode
import org.yaml.snakeyaml.nodes.SequenceNode
import org.yaml.snakeyaml.nodes.Tag
import java.io.Writer
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.util.*

/**
 * Emits the connection-properties YAML data file consumed by the
 * `param-table` Hugo shortcode. The output shape is a flat list of dicts
 * with known keys; we build the snakeyaml node tree directly so that key
 * order, scalar styles (folded descriptions, flow-style tag lists,
 * always-quoted default strings) and the wrap width are all controlled
 * explicitly.
 */
internal object YamlEmitter {

    /** Hard-wrap column for folded description scalars. */
    private const val WRAP = 78

    fun writeTo(records: List<PropertyRecord>, output: Path) {
        Files.createDirectories(output.parent)
        Files.newBufferedWriter(output, StandardCharsets.UTF_8).use { w ->
            writeHeader(w)
            Yaml(dumperOptions()).serialize(buildSequence(records), w)
        }
    }

    private fun dumperOptions() = DumperOptions().apply {
        defaultFlowStyle = FlowStyle.BLOCK
        indent = 2
        indicatorIndent = 0
        width = WRAP
        splitLines = true
        lineBreak = DumperOptions.LineBreak.UNIX
    }

    private fun writeHeader(w: Writer) {
        w.write("# Generated by :docs-tools:generateProperties — DO NOT EDIT.\n")
        w.write("# Source of truth: pgjdbc/src/main/java/org/postgresql/PGProperty.java\n")
        w.write("#                  + @PgApi / @PgTags / @PgPropertyType annotations on each value.\n")
        w.write("# Run `./gradlew :docs-tools:generateProperties` to regenerate.\n")
        w.write("\n")
    }

    private fun buildSequence(records: List<PropertyRecord>): SequenceNode =
        SequenceNode(Tag.SEQ, true, records.map(::buildMapping), null, null, FlowStyle.BLOCK)

    private fun buildMapping(r: PropertyRecord): MappingNode = MappingNode(
        Tag.MAP,
        true,
        buildList {
            add(tuple("name", str(r.name)))
            add(tuple("type", str(r.type)))
            add(tuple("default", defaultNode(r.defaultValue)))
            add(tuple("introducedIn", str(r.introducedIn)))
            add(tuple("status", str(r.status)))
            if (r.deprecatedIn.isNotEmpty()) add(tuple("deprecatedIn", str(r.deprecatedIn)))
            if (r.hiddenIn.isNotEmpty())     add(tuple("hiddenIn", str(r.hiddenIn)))
            add(tuple("tags", flowList(r.tags.map { it.lowercase(Locale.ROOT) })))
            r.choices
                ?.takeIf { it.isNotEmpty() }
                ?.let { add(tuple("choices", flowList(it.toList()))) }
            if (r.required) add(tuple("required", bool(true)))
            add(tuple("description", folded(r.description)))
        },
        null, null, FlowStyle.BLOCK,
    )

    /* ----- Node helpers --------------------------------------------------- */

    private fun tuple(key: String, value: Node): NodeTuple =
        NodeTuple(scalar(Tag.STR, key, ScalarStyle.PLAIN), value)

    /**
     * Plain string scalar. snakeyaml's emitter promotes the value to a
     * quoted style on its own when a plain rendering would round-trip as
     * a non-string (e.g. "false", "null", "9.4").
     */
    private fun str(s: String?): Node =
        if (s.isNullOrEmpty()) scalar(Tag.STR, "", ScalarStyle.DOUBLE_QUOTED)
        else scalar(Tag.STR, s, ScalarStyle.PLAIN)

    /**
     * Defaults need special handling: a `null` default is rendered as the
     * YAML `null` scalar; every other default is forced to a double-quoted
     * string so numeric/boolean-looking values stay strings on the consumer
     * side (consistent with how PGProperty stores them).
     */
    private fun defaultNode(d: String?): Node =
        if (d == null) scalar(Tag.NULL, "null", ScalarStyle.PLAIN)
        else scalar(Tag.STR, d, ScalarStyle.DOUBLE_QUOTED)

    private fun bool(v: Boolean): Node =
        scalar(Tag.BOOL, v.toString(), ScalarStyle.PLAIN)

    /**
     * Render the (possibly long, possibly multi-line) description as a
     * folded-and-stripped block scalar (`>-`). All embedded whitespace is
     * normalised to single spaces so the emitter re-wraps cleanly at [WRAP].
     */
    private fun folded(text: String?): Node {
        if (text.isNullOrEmpty()) return scalar(Tag.STR, "", ScalarStyle.DOUBLE_QUOTED)
        val normalised = text.replace(Regex("\\s+"), " ").trim()
        return scalar(Tag.STR, normalised, ScalarStyle.FOLDED)
    }

    private fun flowList(items: List<String>): Node =
        SequenceNode(Tag.SEQ, true, items.map(::str), null, null, FlowStyle.FLOW)

    private fun scalar(tag: Tag, value: String, style: ScalarStyle): ScalarNode =
        ScalarNode(tag, value, null, null, style)
}
