/*
 * Copyright (c) 2026, PostgreSQL Global Development Group
 * See the LICENSE file in the project root for more information.
 */

package org.postgresql.tools.docs

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Path
import kotlin.io.path.readText

class YamlEmitterTest {

    @TempDir lateinit var tmp: Path

    @Test fun `simple stable property round-trips through snakeyaml`() {
        val out = tmp.resolve("connection-properties.yaml")
        YamlEmitter.writeTo(listOf(propertyRecord()), out)
        val yaml = out.readText()

        // Header preamble survives untouched.
        assertTrue(yaml.startsWith("# Generated by :docs-tools:generateProperties"),
            "missing header preamble in:\n$yaml")
        // Body: each field on its own line, BOOLEAN unquoted, default quoted,
        // tags as flow list lowercased, description folded.
        val body = yaml.substringAfter("\n\n")
        assertEquals(
            """
            - name: adaptiveFetch
              type: BOOLEAN
              default: "false"
              introducedIn: 42.2.11
              status: STABLE
              tags: [fetch, network]
              description: >-
                Specifies if number of rows fetched in ResultSet should be adaptive.
            """.trimIndent() + "\n",
            body,
        )
    }

    @Test fun `null default renders as YAML null and choices as flow list`() {
        val out = tmp.resolve("out.yaml")
        YamlEmitter.writeTo(
            listOf(propertyRecord(
                fieldName = "AUTOSAVE",
                name = "autosave",
                type = "ENUM",
                defaultValue = "never",
                choices = arrayOf("always", "never", "conservative"),
                description = "How to handle failed queries.",
                tags = listOf("TRANSACTION"),
            )),
            out,
        )
        val yaml = out.readText()
        assertTrue(yaml.contains("default: \"never\""), yaml)
        assertTrue(yaml.contains("choices: [always, never, conservative]"), yaml)
        assertTrue(yaml.contains("tags: [transaction]"), yaml)
    }

    @Test fun `deprecated and hidden render only when non-empty`() {
        val out = tmp.resolve("out.yaml")
        YamlEmitter.writeTo(
            listOf(
                propertyRecord(),
                propertyRecord(
                    fieldName = "LOGGER_LEVEL",
                    name = "loggerLevel",
                    status = "DEPRECATED",
                    deprecatedIn = "42.0.0",
                ),
            ),
            out,
        )
        val yaml = out.readText()
        // First record has no deprecatedIn/hiddenIn lines.
        val first = yaml.substringAfter("\n\n").substringBefore("- name: loggerLevel")
        assertTrue("deprecatedIn" !in first, "first record should not carry deprecatedIn:\n$first")
        // Second one does.
        assertTrue("deprecatedIn: 42.0.0" in yaml, yaml)
    }

    @Test fun `null default is preserved as YAML null scalar`() {
        val out = tmp.resolve("out.yaml")
        YamlEmitter.writeTo(
            listOf(propertyRecord(defaultValue = null)),
            out,
        )
        assertTrue(out.readText().contains("default: null"), out.readText())
    }

    @Test fun `required true renders as a real YAML boolean`() {
        val out = tmp.resolve("out.yaml")
        YamlEmitter.writeTo(
            listOf(propertyRecord(required = true)),
            out,
        )
        // Real boolean — unquoted true.
        assertTrue(out.readText().contains("required: true\n"), out.readText())
    }
}
