import java.time.LocalDate

plugins {
    id("java")
    id("build-logic.test-base")
    id("build-logic.build-params")
    id("build-logic.style")
    id("com.github.vlsi.jandex")
}

repositories {
    if (buildParameters.enableMavenLocal) {
        mavenLocal()
    }
    mavenCentral {
        mavenContent {
            releasesOnly()
        }
    }
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
        mavenContent {
            snapshotsOnly()
        }
    }
}

java {
    toolchain {
        configureToolchain(buildParameters.buildJdk)
    }
}

tasks.withType<JavaExec>().configureEach {
    buildParameters.testJdk?.let {
        javaLauncher.convention(javaToolchains.launcherFor(it))
    }
}

sourceSets {
    main {
        resources {
            // TODO: remove when LICENSE is removed (it is used by Maven build for now)
            exclude("META-INF/LICENSE")
        }
    }
}

project.configure<com.github.vlsi.jandex.JandexExtension> {
    skipIndexFileGeneration()
}

if (!buildParameters.enableGradleMetadata) {
    tasks.withType<GenerateModuleMetadata>().configureEach {
        enabled = false
    }
}

if (buildParameters.coverage || gradle.startParameter.taskNames.any { it.contains("jacoco") }) {
    apply(plugin = "build-logic.jacoco")
}

tasks.withType<JavaCompile>().configureEach {
    options.apply {
        encoding = "UTF-8"
        // Use --release=8 for Java 10+ so the generated bytecode does not include methods introduced in Java 9+
        release.set(
            provider {
                buildParameters.targetJavaVersion.takeIf {
                    javaCompiler.get().metadata.languageVersion.asInt() > 9
                }
            }
        )
        compilerArgs.add("-parameters")
        if (buildParameters.jdkBuildVersion >= 21 && buildParameters.targetJavaVersion < 11) {
            // We know target Java 8 is deprecated with Java 21, so silence the warning
            // otherwise the build fails due to -Werror below
            compilerArgs.add("-Xlint:-options")
        }
        if (!buildParameters.enableCheckerframework) {
            compilerArgs.add("-Xlint:deprecation")
        } else {
            // We use checkerframework for nullability mostly, so we don't want to see deprecation warnings
            compilerArgs.add("-Xmaxerrs")
            compilerArgs.add("1")
        }
        if (buildParameters.failOnJavacWarning) {
            compilerArgs.add("-Werror")
        }
    }
}

tasks.withType<Javadoc>().configureEach {
    (options as StandardJavadocDocletOptions).apply {
        // Please refrain from using non-ASCII chars below since the options are passed as
        // javadoc.options file which is parsed with "default encoding"
        noTimestamp.value = true
        showFromProtected()
        if (buildParameters.failOnJavadocWarning) {
            // See JDK-8200363 (https://bugs.openjdk.java.net/browse/JDK-8200363)
            // for information about the -Xwerror option.
            addBooleanOption("Xwerror", true)
        }
        // There are too many missing javadocs, so failing the build on missing comments seems to be not an option
        addBooleanOption("Xdoclint:all,-missing", true)
        // javadoc: error - The code being documented uses modules but the packages
        // defined in https://docs.oracle.com/javase/9/docs/api/ are in the unnamed module
        source = "1.8"
        docEncoding = "UTF-8"
        charSet = "UTF-8"
        encoding = "UTF-8"
        docTitle = "PostgreSQL JDBC ${project.name} API version ${project.version}"
        windowTitle = "PostgreSQL JDBC ${project.name} API version ${project.version}"
        header = "<b>PostgreSQL JDBC</b>"
        val lastEditYear = providers.gradleProperty("lastEditYear")
            .getOrElse(LocalDate.now().year.toString())
        bottom =
            "Copyright &copy; 1997-$lastEditYear PostgreSQL Global Development Group. All Rights Reserved."
        if (buildParameters.buildJdkVersion >= 17) {
            addBooleanOption("html5", true)
        } else if (buildParameters.buildJdkVersion >= 9) {
            addBooleanOption("html5", true)
            links("https://docs.oracle.com/en/java/javase/11/docs/api/")
        } else {
            links("https://docs.oracle.com/javase/8/docs/api/")
        }
    }
}

// Add default license/notice when missing (e.g. see :src:config that overrides LICENSE)

afterEvaluate {
    tasks.withType<Jar>().configureEach {
        into("META-INF") {
            filteringCharset = "UTF-8"
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
            from("$rootDir/LICENSE")
            from("$rootDir/NOTICE")
        }
    }
}

tasks.withType<Jar>().configureEach {
    manifest {
        attributes["Bundle-License"] = "BSD-2-Clause"
        attributes["Implementation-Title"] = "PostgreSQL JDBC Driver"
        attributes["Implementation-Version"] = project.version
        val jdbcSpec = (project.findProperty("jdbc.specification.version") as? String) ?: ""
        if (jdbcSpec.isNotBlank()) {
            attributes["Specification-Vendor"] = "Oracle Corporation"
            attributes["Specification-Version"] = jdbcSpec
            attributes["Specification-Title"] = "JDBC"
        }
        attributes["Implementation-Vendor"] = "PostgreSQL Global Development Group"
        attributes["Implementation-Vendor-Id"] = "org.postgresql"
    }
}
