name: Dependency Submission

# See https://github.com/gradle/actions/blob/768a17f3488dc3fe0155ff431553e1f53d57e22e/dependency-submission/README.md#the-dependency-submission-action
# The action allows GitHub to alert about reported vulnerabilities in the project
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Submit dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: zulu
        java-version: 21
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
