### GLOBAL ITEMS

[[global]]
    name="Download"
    weight=1
    identifier="download"
    url="/download/"

[[global]]
    name="Documentation"
    weight=2
    identifier="document"
    url="/documentation/"

[[global]]
    name="Community"
    weight=3
    identifier="community"
    url="/community/"

[[global]]
    name="Development"
    weight=1
    identifier="development"
    url="/development/"

### DOCS ITEMS

[[docs]]
    name="Introduction"
    weight=1
    identifier="chapter1"
    url="/documentation/chapter1/"

[[docs]]
    name="Setting up the JDBC Driver"
    weight=2
    identifier="chapter2"
    url="/documentation/chapter2/"

[[docs]]
    name="Initializing the Driver"
    weight=3
    identifier="chapter3"
    url="/documentation/chapter3/"

[[docs]]
    name="Using SSL"
    weight=4
    identifier="chapter4"
    url="/documentation/chapter4/"

[[docs]]
    name="Issuing a Query and Processing the Result"
    weight=5
    identifier="chapter5"
    url="/documentation/chapter5/"

[[docs]]
    name="Calling Stored Functions and Procedures"
    weight=6
    identifier="chapter6"
    url="/documentation/chapter6/"

[[docs]]
    name="Storing Binary Data"
    weight=7
    identifier="chapter7"
    url="/documentation/chapter7/"

[[docs]]
    name="JDBC escapes"
    weight=8
    identifier="chapter8"
    url="/documentation/chapter8/"

[[docs]]
    name="PostgreSQL™ Extensions to the JDBC API"
    weight=9
    identifier="chapter9"
    url="/documentation/chapter9/"

[[docs]]
    name="Using the Driver in a Multithreaded or a Servlet Environment"
    weight=10
    identifier="chapter10"
    url="/documentation/chapter10/"

[[docs]]
    name="Connection Pools and Data Sources"
    weight=11
    identifier="chapter11"
    url="/documentation/chapter11/"

[[docs]]
    name="Logging using java.util.logging"
    weight=12
    identifier="chapter12"
    url="/documentation/chapter12/"

[[docs]]
    name="Further Reading"
    weight=13
    identifier="chapter13"
    url="/documentation/chapter13/"