/* Automatically generated by GNU msgfmt.  Do not modify!  */
package org.postgresql.translation;
public class messages_cs extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[346];
    t[0] = "";
    t[1] = "Project-Id-Version: PostgreSQL JDBC Driver 8.0\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2005-08-21 20:00+0200\nLast-Translator: Petr Dittrich <bodyn@medoro.org>\nLanguage-Team: \nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n";
    t[2] = "Can''t refresh the insert row.";
    t[3] = "Nemohu obnovit vkládaný řádek.";
    t[6] = "There are no rows in this ResultSet.";
    t[7] = "Žádný řádek v ResultSet.";
    t[8] = "Invalid character data was found.  This is most likely caused by stored data containing characters that are invalid for the character set the database was created in.  The most common example of this is storing 8bit data in a SQL_ASCII database.";
    t[9] = "Nalezena vada ve znakových datech. Toto může být způsobeno uloženými daty obsahujícími znaky, které jsou závadné pro znakovou sadu nastavenou při zakládání databáze. Nejznámejší příklad je ukládání 8bitových dat vSQL_ASCII databázi.";
    t[10] = "Malformed function or procedure escape syntax at offset {0}.";
    t[11] = "Poškozená funkce nebo opuštění procedury na pozici {0}.";
    t[14] = "An error occurred while setting up the SSL connection.";
    t[15] = "Nastala chyba při nastavení SSL spojení.";
    t[16] = "Cannot cast an instance of {0} to type {1}";
    t[17] = "Nemohu přetypovat instanci {0} na typ {1}";
    t[20] = "Invalid stream length {0}.";
    t[21] = "Vadná délka proudu {0}.";
    t[24] = "Unexpected command status: {0}.";
    t[25] = "Neočekávaný stav příkazu: {0}.";
    t[32] = "A connection could not be made using the requested protocol {0}.";
    t[33] = "Spojení nelze vytvořit s použitím žádaného protokolu {0}.";
    t[36] = "{0} function takes two or three arguments.";
    t[37] = "Funkce {0} bere dva nebo tři argumenty.";
    t[38] = "Bad value for type {0} : {1}";
    t[39] = "Špatná hodnota pro typ {0} : {1}";
    t[40] = "An I/O error occurred while sending to the backend.";
    t[41] = "Vystupně/výstupní chyba při odesílání k backend.";
    t[48] = "Unknown type {0}.";
    t[49] = "Neznámý typ {0}.";
    t[52] = "The server does not support SSL.";
    t[53] = "Server nepodporuje SSL.";
    t[56] = "No results were returned by the query.";
    t[57] = "Neobdržen žádný výsledek dotazu.";
    t[60] = "Cannot call updateRow() when on the insert row.";
    t[61] = "Nemohu volat updateRow() na vlkádaném řádku.";
    t[62] = "Where: {0}";
    t[63] = "Kde: {0}";
    t[66] = "The array index is out of range: {0}, number of elements: {1}.";
    t[67] = "Index pole mimo rozsah: {0}, počet prvků: {1}.";
    t[68] = "Not on the insert row.";
    t[69] = "Ne na vkládaném řádku.";
    t[72] = "Cannot call cancelRowUpdates() when on the insert row.";
    t[73] = "Nemůžete volat cancelRowUpdates() při vkládání řádku.";
    t[82] = "Server SQLState: {0}";
    t[83] = "Server SQLState: {0}";
    t[84] = "The SSLSocketFactory class provided {0} could not be instantiated.";
    t[85] = "Třída SSLSocketFactory poskytla {0} což nemůže být instancionizováno.";
    t[88] = "The maximum field size must be a value greater than or equal to 0.";
    t[89] = "Maximální velikost pole musí být nezáporné číslo.";
    t[92] = "ResultSet is not updateable.  The query that generated this result set must select only one table, and must select all primary keys from that table. See the JDBC 2.1 API Specification, section 5.6 for more details.";
    t[93] = "ResultSet není aktualizavatelný. Dotaz musí vybírat pouze z jedné tabulky a musí obsahovat všechny primární klíče tabulky. Koukni do JDBC 2.1 API Specifikace, sekce 5.6 pro více podrobností.";
    t[100] = "ResultSets with concurrency CONCUR_READ_ONLY cannot be updated.";
    t[101] = "ResultSets se souběžností CONCUR_READ_ONLY nemůže být aktualizováno";
    t[108] = "The parameter index is out of range: {0}, number of parameters: {1}.";
    t[109] = "Index parametru mimo rozsah: {0}, počet parametrů {1}.";
    t[110] = "Unsupported Types value: {0}";
    t[111] = "Nepodporovaná hodnota typu: {0}";
    t[112] = "Currently positioned after the end of the ResultSet.  You cannot call deleteRow() here.";
    t[113] = "Právě jste za pozicí konce ResultSetu. Zde nemůžete volat deleteRow().s";
    t[114] = "This ResultSet is closed.";
    t[115] = "Tento ResultSet je uzavřený.";
    t[122] = "Unable to load the class {0} responsible for the datatype {1}";
    t[123] = "Nemohu načíst třídu {0} odpovědnou za typ {1}";
    t[126] = "The column name {0} was not found in this ResultSet.";
    t[127] = "Sloupec pojmenovaný {0} nebyl nalezen v ResultSet.";
    t[134] = "LOB positioning offsets start at 1.";
    t[135] = "Začátek pozicování LOB začína na 1.";
    t[138] = "Error loading default settings from driverconfig.properties";
    t[139] = "Chyba načítání standardního nastavení z driverconfig.properties";
    t[142] = "The array index is out of range: {0}";
    t[143] = "Index pole mimo rozsah: {0}";
    t[144] = "Detail: {0}";
    t[145] = "Detail: {0}";
    t[146] = "Unknown Types value.";
    t[147] = "Neznámá hodnota typu.";
    t[150] = "Large Objects may not be used in auto-commit mode.";
    t[151] = "Velké objecky nemohou být použity v auto-commit modu.";
    t[152] = "You must specify at least one column value to insert a row.";
    t[153] = "Musíte vyplnit alespoň jeden sloupec pro vložení řádku.";
    t[154] = "Unable to translate data into the desired encoding.";
    t[155] = "Nemohu přeložit data do požadovaného kódování.";
    t[156] = "{0} function takes one and only one argument.";
    t[157] = "Funkce {0} bere jeden argument.";
    t[160] = "Cannot reference a savepoint after it has been released.";
    t[161] = "Nemohu získat odkaz na savepoint, když byl uvolněn.";
    t[168] = "Cannot retrieve the id of a named savepoint.";
    t[169] = "Nemohu získat id nepojmenovaného savepointu.";
    t[170] = "Unknown Response Type {0}.";
    t[171] = "Neznámý typ odpovědi {0}.";
    t[178] = "Invalid fetch direction constant: {0}.";
    t[179] = "Špatný směr čtení: {0}.";
    t[180] = "Multiple ResultSets were returned by the query.";
    t[181] = "Vícenásobný ResultSet byl vrácen dotazem.";
    t[184] = "Query timeout must be a value greater than or equals to 0.";
    t[185] = "Časový limit dotazu musí být nezáporné číslo.";
    t[186] = "Too many update results were returned.";
    t[187] = "Bylo vráceno příliš mnoho výsledků aktualizací.";
    t[190] = "The connection attempt failed.";
    t[191] = "Pokus o připojení selhal.";
    t[204] = "Protocol error.  Session setup failed.";
    t[205] = "Chyba protokolu. Nastavení relace selhalo.";
    t[206] = "This PooledConnection has already been closed.";
    t[207] = "Tento PooledConnection byl uzavřen.";
    t[208] = "DataSource has been closed.";
    t[209] = "DataSource byl uzavřen.";
    t[210] = "Unable to find name datatype in the system catalogs.";
    t[211] = "Nemohu najít název typu v systémovém katalogu.";
    t[212] = "Method {0} is not yet implemented.";
    t[213] = "Metoda {0} není implementována.";
    t[216] = "Hint: {0}";
    t[217] = "Rada: {0}";
    t[218] = "No value specified for parameter {0}.";
    t[219] = "Nespecifikována hodnota parametru {0}.";
    t[222] = "Position: {0}";
    t[223] = "Pozice: {0}";
    t[224] = "Can''t use relative move methods while on the insert row.";
    t[225] = "Nemůžete používat relativní přesuny při vkládání řádku.";
    t[226] = "Cannot call deleteRow() when on the insert row.";
    t[227] = "Nemůžete volat deleteRow() při vkládání řádku.";
    t[228] = "Cannot establish a savepoint in auto-commit mode.";
    t[229] = "Nemohu vytvořit savepoint v auto-commit modu.";
    t[240] = "The JVM claims not to support the encoding: {0}";
    t[241] = "JVM tvrdí, že nepodporuje kodování: {0}";
    t[248] = "Connection has been closed.";
    t[249] = "Spojeni bylo uzavřeno.";
    t[254] = "Unexpected error writing large object to database.";
    t[255] = "Neočekávaná chyba při zapisování velkého objektu do databáze.";
    t[256] = "This statement has been closed.";
    t[257] = "Příkaz byl uzavřen.";
    t[258] = "Failed to create object for: {0}.";
    t[259] = "Selhalo vytvoření objektu: {0}.";
    t[270] = "Statement has been closed.";
    t[271] = "Statement byl uzavřen.";
    t[276] = "The authentication type {0} is not supported. Check that you have configured the pg_hba.conf file to include the client''s IP address or subnet, and that it is using an authentication scheme supported by the driver.";
    t[277] = "Ověření typu {0} není podporováno. Zkontrolujte zda konfigurační soubor pg_hba.conf obsahuje klientskou IP adresu či podsíť a zda je použité ověřenovací schéma podporováno ovladačem.";
    t[278] = "A CallableStatement was executed with nothing returned.";
    t[279] = "CallableStatement byl spuštěn, leč nic nebylo vráceno.";
    t[282] = "A result was returned when none was expected.";
    t[283] = "Obdržen výsledek, ikdyž žádný nebyl očekáván.";
    t[294] = "{0} function takes two and only two arguments.";
    t[295] = "Funkce {0} bere právě dva argumenty.";
    t[304] = "Provided Reader failed.";
    t[305] = "Selhal poskytnutý Reader.";
    t[306] = "Fetch size must be a value greater than or equal to 0.";
    t[307] = "Nabraná velikost musí být nezáporná.";
    t[308] = "Location: File: {0}, Routine: {1}, Line: {2}";
    t[309] = "Poloha: Soubor: {0}, Rutina: {1}, Řádek: {2}";
    t[310] = "Cannot retrieve the name of an unnamed savepoint.";
    t[311] = "Nemohu získat název nepojmenovaného savepointu.";
    t[312] = "Returning autogenerated keys is not supported.";
    t[313] = "Vrácení automaticky generovaných klíčů není podporováno.";
    t[314] = "An unexpected result was returned by a query.";
    t[315] = "Obdržen neočekávaný výsledek dotazu.";
    t[316] = "The column index is out of range: {0}, number of columns: {1}.";
    t[317] = "Index sloupece je mimo rozsah: {0}, počet sloupců: {1}.";
    t[318] = "Expected command status BEGIN, got {0}.";
    t[319] = "Očekáván příkaz BEGIN, obdržen {0}.";
    t[324] = "Conversion of money failed.";
    t[325] = "Převod peněz selhal.";
    t[326] = "The JVM claims not to support the {0} encoding.";
    t[327] = "JVM tvrdí, že nepodporuje kodování {0}.";
    t[332] = "{0} function takes four and only four argument.";
    t[333] = "Funkce {0} bere přesně čtyři argumenty.";
    t[334] = "{0} function doesn''t take any argument.";
    t[335] = "Funkce {0} nebere žádný argument.";
    t[336] = "Provided InputStream failed.";
    t[337] = "Selhal poskytnutý InputStream.";
    t[338] = "Something unusual has occurred to cause the driver to fail. Please report this exception.";
    t[339] = "Něco neobvyklého přinutilo ovladač selhat. Prosím nahlaste tuto vyjímku.";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 173) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 171) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 346)
        idx -= 346;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 346 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 346);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 346 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
