/* Automatically generated by GNU msgfmt.  Do not modify!  */
package org.postgresql.translation;
public class messages_cs extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[314];
    t[0] = "";
    t[1] = "Project-Id-Version: PostgreSQL JDBC Driver 8.0\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2005-08-21 20:00+0200\nLast-Translator: Petr Dittrich <bodyn@medoro.org>\nLanguage-Team: \nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n";
    t[2] = "A connection could not be made using the requested protocol {0}.";
    t[3] = "Spojenďż˝ nelze vytvoďż˝it s pouďż˝itďż˝m ďż˝ďż˝danďż˝ho protokolu {0}.";
    t[4] = "Malformed function or procedure escape syntax at offset {0}.";
    t[5] = "Poďż˝kozenďż˝ funkce nebo opuďż˝tďż˝nďż˝ procedury na pozici {0}.";
    t[8] = "Cannot cast an instance of {0} to type {1}";
    t[9] = "Nemohu pďż˝etypovat instanci {0} na typ {1}";
    t[12] = "ResultSet is not updateable.  The query that generated this result set must select only one table, and must select all primary keys from that table. See the JDBC 2.1 API Specification, section 5.6 for more details.";
    t[13] = "ResultSet nenďż˝ aktualizavatelnďż˝. Dotaz musďż˝ vybďż˝rat pouze z jednďż˝ tabulky a musďż˝ obsahovat vďż˝echny primďż˝rnďż˝ klďż˝ďż˝e tabulky. Koukni do JDBC 2.1 API Specifikace, sekce 5.6 pro vďż˝ce podrobnostďż˝.";
    t[14] = "The JVM claims not to support the {0} encoding.";
    t[15] = "JVM tvrdďż˝, ďż˝e nepodporuje kodovďż˝nďż˝ {0}.";
    t[16] = "An I/O error occurred while sending to the backend.";
    t[17] = "Vystupnďż˝/vďż˝stupnďż˝ chyba pďż˝i odesďż˝lďż˝nďż˝ k backend.";
    t[18] = "Statement has been closed.";
    t[19] = "Statement byl uzavďż˝en.";
    t[20] = "Unknown Types value.";
    t[21] = "Neznďż˝mďż˝ hodnota typu.";
    t[22] = "ResultSets with concurrency CONCUR_READ_ONLY cannot be updated.";
    t[23] = "ResultSets se soubďż˝nostďż˝ CONCUR_READ_ONLY nemďż˝ďż˝e bďż˝t aktualizovďż˝no";
    t[26] = "You must specify at least one column value to insert a row.";
    t[27] = "Musďż˝te vyplnit alespoďż˝ jeden sloupec pro vloďż˝enďż˝ ďż˝ďż˝dku.";
    t[32] = "No primary key found for table {0}.";
    t[33] = "Nenalezen primďż˝rnďż˝ klďż˝ďż˝ pro tabulku {0}.";
    t[34] = "Cannot establish a savepoint in auto-commit mode.";
    t[35] = "Nemohu vytvoďż˝it savepoint v auto-commit modu.";
    t[38] = "Can''t use relative move methods while on the insert row.";
    t[39] = "Nemďż˝ďż˝ete pouďż˝ďż˝vat relativnďż˝ pďż˝esuny pďż˝i vklďż˝dďż˝nďż˝ ďż˝ďż˝dku.";
    t[44] = "The column name {0} was not found in this ResultSet.";
    t[45] = "Sloupec pojmenovanďż˝ {0} nebyl nalezen v ResultSet.";
    t[46] = "This statement has been closed.";
    t[47] = "Pďż˝ďż˝kaz byl uzavďż˝en.";
    t[48] = "The SSLSocketFactory class provided {0} could not be instantiated.";
    t[49] = "Tďż˝ďż˝da SSLSocketFactory poskytla {0} coďż˝ nemďż˝ďż˝e bďż˝t instancionizovďż˝no.";
    t[50] = "Multiple ResultSets were returned by the query.";
    t[51] = "Vďż˝cenďż˝sobnďż˝ ResultSet byl vrďż˝cen dotazem.";
    t[52] = "DataSource has been closed.";
    t[53] = "DataSource byl uzavďż˝en.";
    t[56] = "Error loading default settings from driverconfig.properties";
    t[57] = "Chyba naďż˝ďż˝tďż˝nďż˝ standardnďż˝ho nastavenďż˝ z driverconfig.properties";
    t[62] = "Bad value for type {0} : {1}";
    t[63] = "ďż˝patnďż˝ hodnota pro typ {0} : {1}";
    t[66] = "Method {0} is not yet implemented.";
    t[67] = "Metoda {0} nenďż˝ implementovďż˝na.";
    t[68] = "The array index is out of range: {0}";
    t[69] = "Index pole mimo rozsah: {0}";
    t[70] = "Unexpected command status: {0}.";
    t[71] = "Neoďż˝ekďż˝vanďż˝ stav pďż˝ďż˝kazu: {0}.";
    t[74] = "Expected command status BEGIN, got {0}.";
    t[75] = "Oďż˝ekďż˝vďż˝n pďż˝ďż˝kaz BEGIN, obdrďż˝en {0}.";
    t[76] = "Cannot retrieve the id of a named savepoint.";
    t[77] = "Nemohu zďż˝skat id nepojmenovanďż˝ho savepointu.";
    t[78] = "Unexpected error writing large object to database.";
    t[79] = "Neoďż˝ekďż˝vanďż˝ chyba pďż˝i zapisovďż˝nďż˝ velkďż˝ho objektu do databďż˝ze.";
    t[84] = "Not on the insert row.";
    t[85] = "Ne na vklďż˝danďż˝m ďż˝ďż˝dku.";
    t[86] = "Returning autogenerated keys is not supported.";
    t[87] = "Vrďż˝cenďż˝ automaticky generovanďż˝ch klďż˝ďż˝ďż˝ nenďż˝ podporovďż˝no.";
    t[88] = "The server requested password-based authentication, but no password was provided.";
    t[89] = "Server vyďż˝aduje ovďż˝ďż˝enďż˝ heslem, ale ďż˝ďż˝dnďż˝ nebylo poslďż˝no.";
    t[98] = "Unable to load the class {0} responsible for the datatype {1}";
    t[99] = "Nemohu naďż˝ďż˝st tďż˝ďż˝du {0} odpovďż˝dnou za typ {1}";
    t[100] = "Invalid fetch direction constant: {0}.";
    t[101] = "ďż˝patnďż˝ smďż˝r ďż˝tenďż˝: {0}.";
    t[102] = "Conversion of money failed.";
    t[103] = "Pďż˝evod penďż˝z selhal.";
    t[104] = "Connection has been closed.";
    t[105] = "Spojeni bylo uzavďż˝eno.";
    t[106] = "Cannot retrieve the name of an unnamed savepoint.";
    t[107] = "Nemohu zďż˝skat nďż˝zev nepojmenovanďż˝ho savepointu.";
    t[108] = "Large Objects may not be used in auto-commit mode.";
    t[109] = "Velkďż˝ objecky nemohou bďż˝t pouďż˝ity v auto-commit modu.";
    t[110] = "This ResultSet is closed.";
    t[111] = "Tento ResultSet je uzavďż˝enďż˝.";
    t[116] = "Something unusual has occurred to cause the driver to fail. Please report this exception.";
    t[117] = "Nďż˝co neobvyklďż˝ho pďż˝inutilo ovladaďż˝ selhat. Prosďż˝m nahlaste tuto vyjďż˝mku.";
    t[118] = "The server does not support SSL.";
    t[119] = "Server nepodporuje SSL.";
    t[120] = "Invalid stream length {0}.";
    t[121] = "Vadnďż˝ dďż˝lka proudu {0}.";
    t[126] = "The maximum field size must be a value greater than or equal to 0.";
    t[127] = "Maximďż˝lnďż˝ velikost pole musďż˝ bďż˝t nezďż˝pornďż˝ ďż˝ďż˝slo.";
    t[130] = "Cannot call updateRow() when on the insert row.";
    t[131] = "Nemohu volat updateRow() na vlkďż˝danďż˝m ďż˝ďż˝dku.";
    t[132] = "A CallableStatement was executed with nothing returned.";
    t[133] = "CallableStatement byl spuďż˝tďż˝n, leďż˝ nic nebylo vrďż˝ceno.";
    t[134] = "Provided Reader failed.";
    t[135] = "Selhal poskytnutďż˝ Reader.";
    t[146] = "Cannot call deleteRow() when on the insert row.";
    t[147] = "Nemďż˝ďż˝ete volat deleteRow() pďż˝i vklďż˝dďż˝nďż˝ ďż˝ďż˝dku.";
    t[156] = "Where: {0}";
    t[157] = "Kde: {0}";
    t[158] = "An unexpected result was returned by a query.";
    t[159] = "Obdrďż˝en neoďż˝ekďż˝vanďż˝ vďż˝sledek dotazu.";
    t[160] = "The connection attempt failed.";
    t[161] = "Pokus o pďż˝ipojenďż˝ selhal.";
    t[162] = "Too many update results were returned.";
    t[163] = "Bylo vrďż˝ceno pďż˝ďż˝liďż˝ mnoho vďż˝sledkďż˝ aktualizacďż˝.";
    t[164] = "Unknown type {0}.";
    t[165] = "Neznďż˝mďż˝ typ {0}.";
    t[166] = "{0} function takes two and only two arguments.";
    t[167] = "Funkce {0} bere prďż˝vďż˝ dva argumenty.";
    t[168] = "{0} function doesn''t take any argument.";
    t[169] = "Funkce {0} nebere ďż˝ďż˝dnďż˝ argument.";
    t[172] = "Unable to find name datatype in the system catalogs.";
    t[173] = "Nemohu najďż˝t nďż˝zev typu v systďż˝movďż˝m katalogu.";
    t[174] = "Protocol error.  Session setup failed.";
    t[175] = "Chyba protokolu. Nastavenďż˝ relace selhalo.";
    t[176] = "{0} function takes one and only one argument.";
    t[177] = "Funkce {0} bere jeden argument.";
    t[190] = "Invalid character data was found.  This is most likely caused by stored data containing characters that are invalid for the character set the database was created in.  The most common example of this is storing 8bit data in a SQL_ASCII database.";
    t[191] = "Nalezena vada ve znakovďż˝ch datech. Toto mďż˝ďż˝e bďż˝t zpďż˝sobeno uloďż˝enďż˝mi daty obsahujďż˝cďż˝mi znaky, kterďż˝ jsou zďż˝vadnďż˝ pro znakovou sadu nastavenou pďż˝i zaklďż˝dďż˝nďż˝ databďż˝ze. Nejznďż˝mejďż˝ďż˝ pďż˝ďż˝klad je uklďż˝dďż˝nďż˝ 8bitovďż˝ch dat vSQL_ASCII databďż˝zi.";
    t[196] = "Fetch size must be a value greater to or equal to 0.";
    t[197] = "Nabranďż˝ velikost musďż˝ bďż˝t nezďż˝pornďż˝.";
    t[204] = "Unsupported Types value: {0}";
    t[205] = "Nepodporovanďż˝ hodnota typu: {0}";
    t[206] = "Can''t refresh the insert row.";
    t[207] = "Nemohu obnovit vklďż˝danďż˝ ďż˝ďż˝dek.";
    t[216] = "No value specified for parameter {0}.";
    t[217] = "Nespecifikovďż˝na hodnota parametru {0}.";
    t[218] = "The array index is out of range: {0}, number of elements: {1}.";
    t[219] = "Index pole mimo rozsah: {0}, poďż˝et prvkďż˝: {1}.";
    t[220] = "Provided InputStream failed.";
    t[221] = "Selhal poskytnutďż˝ InputStream.";
    t[228] = "Cannot reference a savepoint after it has been released.";
    t[229] = "Nemohu zďż˝skat odkaz na savepoint, kdyďż˝ byl uvolnďż˝n.";
    t[232] = "An error occurred while setting up the SSL connection.";
    t[233] = "Nastala chyba pďż˝i nastavenďż˝ SSL spojenďż˝.";
    t[244] = "Maximum number of rows must be a value greater than or equal to 0.";
    t[245] = "Maximďż˝lnďż˝ poďż˝et ďż˝ďż˝dek musďż˝ bďż˝t nezďż˝pornďż˝ ďż˝ďż˝slo.";
    t[246] = "Detail: {0}";
    t[247] = "Detail: {0}";
    t[248] = "This PooledConnection has already been closed.";
    t[249] = "Tento PooledConnection byl uzavďż˝en.";
    t[250] = "A result was returned when none was expected.";
    t[251] = "Obdrďż˝en vďż˝sledek, ikdyďż˝ ďż˝ďż˝dnďż˝ nebyl oďż˝ekďż˝vďż˝n.";
    t[254] = "The JVM claims not to support the encoding: {0}";
    t[255] = "JVM tvrdďż˝, ďż˝e nepodporuje kodovďż˝nďż˝: {0}";
    t[256] = "The parameter index is out of range: {0}, number of parameters: {1}.";
    t[257] = "Index parametru mimo rozsah: {0}, poďż˝et parametrďż˝ {1}.";
    t[258] = "LOB positioning offsets start at 1.";
    t[259] = "Zaďż˝ďż˝tek pozicovďż˝nďż˝ LOB zaďż˝ďż˝na na 1.";
    t[260] = "{0} function takes two or three arguments.";
    t[261] = "Funkce {0} bere dva nebo tďż˝i argumenty.";
    t[262] = "Currently positioned after the end of the ResultSet.  You cannot call deleteRow() here.";
    t[263] = "Prďż˝vďż˝ jste za pozicďż˝ konce ResultSetu. Zde nemďż˝ďż˝ete volat deleteRow().s";
    t[266] = "Server SQLState: {0}";
    t[267] = "Server SQLState: {0}";
    t[270] = "{0} function takes four and only four argument.";
    t[271] = "Funkce {0} bere pďż˝esnďż˝ ďż˝tyďż˝i argumenty.";
    t[272] = "Failed to create object for: {0}.";
    t[273] = "Selhalo vytvoďż˝enďż˝ objektu: {0}.";
    t[274] = "No results were returned by the query.";
    t[275] = "Neobdrďż˝en ďż˝ďż˝dnďż˝ vďż˝sledek dotazu.";
    t[276] = "Position: {0}";
    t[277] = "Pozice: {0}";
    t[278] = "The column index is out of range: {0}, number of columns: {1}.";
    t[279] = "Index sloupece je mimo rozsah: {0}, poďż˝et sloupcďż˝: {1}.";
    t[280] = "Unknown Response Type {0}.";
    t[281] = "Neznďż˝mďż˝ typ odpovďż˝di {0}.";
    t[284] = "Hint: {0}";
    t[285] = "Rada: {0}";
    t[286] = "Location: File: {0}, Routine: {1}, Line: {2}";
    t[287] = "Poloha: Soubor: {0}, Rutina: {1}, ďż˝ďż˝dek: {2}";
    t[288] = "Query timeout must be a value greater than or equals to 0.";
    t[289] = "ďż˝asovďż˝ limit dotazu musďż˝ bďż˝t nezďż˝pornďż˝ ďż˝ďż˝slo.";
    t[292] = "Unable to translate data into the desired encoding.";
    t[293] = "Nemohu pďż˝eloďż˝it data do poďż˝adovanďż˝ho kďż˝dovďż˝nďż˝.";
    t[296] = "Cannot call cancelRowUpdates() when on the insert row.";
    t[297] = "Nemďż˝ďż˝ete volat cancelRowUpdates() pďż˝i vklďż˝dďż˝nďż˝ ďż˝ďż˝dku.";
    t[298] = "The authentication type {0} is not supported. Check that you have configured the pg_hba.conf file to include the client''s IP address or subnet, and that it is using an authentication scheme supported by the driver.";
    t[299] = "Ovďż˝ďż˝enďż˝ typu {0} nenďż˝ podporovďż˝no. Zkontrolujte zda konfiguraďż˝nďż˝ soubor pg_hba.conf obsahuje klientskou IP adresu ďż˝i podsďż˝ a zda je pouďż˝itďż˝ ovďż˝ďż˝enovacďż˝ schďż˝ma podporovďż˝no ovladaďż˝em.";
    t[308] = "There are no rows in this ResultSet.";
    t[309] = "ďż˝ďż˝dnďż˝ ďż˝ďż˝dek v ResultSet.";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 157) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 155) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 314)
        idx -= 314;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 314 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 314);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 314 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
