/* Automatically generated by GNU msgfmt.  Do not modify!  */
package org.postgresql.translation;
public class messages_es extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[62];
    t[0] = "";
    t[1] = "Project-Id-Version: JDBC PostgreSQL Driver\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2004-10-22 16:51-0300\nLast-Translator: Diego Gil <diego@adminsa.com>\nLanguage-Team: \nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nX-Poedit-Language: Spanish\n";
    t[6] = "An unexpected result was returned by a query.";
    t[7] = "Una consulta retornó un resultado inesperado.";
    t[8] = "A result was returned when none was expected.";
    t[9] = "Se retornó un resultado cuando no se esperaba ninguno.";
    t[10] = "Something unusual has occurred to cause the driver to fail. Please report this exception.";
    t[11] = "Algo inusual ha ocurrido que provocó un fallo en el controlador. Por favor reporte esta excepción.";
    t[14] = "The server does not support SSL.";
    t[15] = "Este servidor no soporta SSL.";
    t[18] = "No value specified for parameter {0}.";
    t[19] = "No se ha especificado un valor para el parámetro {0}.";
    t[22] = "The array index is out of range: {0}, number of elements: {1}.";
    t[23] = "El índice del arreglo esta fuera de rango: {0}, número de elementos: {1}.";
    t[24] = "Protocol error.  Session setup failed.";
    t[25] = "Error de protocolo. Falló el inicio de la sesión.";
    t[28] = "The column index is out of range: {0}, number of columns: {1}.";
    t[29] = "El índice de la columna está fuera de rango: {0}, número de columnas: {1}.";
    t[36] = "No results were returned by the query.";
    t[37] = "La consulta no retornó ningún resultado.";
    t[38] = "Premature end of input stream, expected {0} bytes, but only read {1}.";
    t[39] = "Final prematuro del flujo de entrada, se esperaban {0} bytes, pero solo se leyeron {1}.";
    t[42] = "Unknown Response Type {0}.";
    t[43] = "Tipo de respuesta desconocida {0}.";
    t[44] = "Server SQLState: {0}";
    t[45] = "SQLState del servidor: {0}.";
    t[46] = "The connection attempt failed.";
    t[47] = "El intento de conexión falló.";
    t[48] = "An error occurred while setting up the SSL connection.";
    t[49] = "Ha ocorrido un error mientras se establecía la conexión SSL.";
    t[56] = "Failed to create object for: {0}.";
    t[57] = "Fallo al crear objeto: {0}.";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 31) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 29) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 62)
        idx -= 62;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 62 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 62);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 62 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
