/* Automatically generated by GNU msgfmt.  Do not modify!  */
package org.postgresql.translation;
public class messages_pl extends java.util.ResourceBundle {
  private static final java.lang.String[] table;
  static {
    java.lang.String[] t = new java.lang.String[242];
    t[0] = "";
    t[1] = "Project-Id-Version: head-pl\nReport-Msgid-Bugs-To: \nPO-Revision-Date: 2005-05-22 03:01+0200\nLast-Translator: Jarosław Jan Pyszny <jarek@pyszny.net>\nLanguage-Team:  <pl@li.org>\nLanguage: \nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nX-Generator: KBabel 1.10\nPlural-Forms:  nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n";
    t[2] = "No value specified for parameter {0}.";
    t[3] = "Nie podano wartości dla parametru {0}.";
    t[4] = "ResultSet not positioned properly, perhaps you need to call next.";
    t[5] = "Zła pozycja w ResultSet, może musisz wywołać next.";
    t[12] = "The column index is out of range: {0}, number of columns: {1}.";
    t[13] = "Indeks kolumny jest poza zakresem: {0}, liczba kolumn: {1}.";
    t[14] = "Hint: {0}";
    t[15] = "Wskazówka: {0}";
    t[20] = "Connection has been closed.";
    t[21] = "Połączenie zostało zamknięte.";
    t[24] = "Unable to load the class {0} responsible for the datatype {1}";
    t[25] = "Nie jest możliwe załadowanie klasy {0} odpowiedzialnej za typ danych {1}";
    t[26] = "Connection has been closed automatically because a new connection was opened for the same PooledConnection or the PooledConnection has been closed.";
    t[27] = "Połączenie zostało zamknięte automatycznie, ponieważ nowe połączenie zostało otwarte dla tego samego PooledConnection lub PooledConnection zostało zamknięte.";
    t[28] = "Unknown Types value.";
    t[29] = "Nieznana wartość Types.";
    t[36] = "Detail: {0}";
    t[37] = "Szczegóły: {0}";
    t[40] = "The server does not support SSL.";
    t[41] = "Serwer nie obsługuje SSL.";
    t[42] = "Unknown Response Type {0}.";
    t[43] = "Nieznany typ odpowiedzi {0}.";
    t[44] = "Internal Query: {0}";
    t[45] = "Wewnętrzne Zapytanie: {0}";
    t[46] = "Location: File: {0}, Routine: {1}, Line: {2}";
    t[47] = "Lokalizacja: Plik: {0}, Procedura: {1}, Linia: {2}";
    t[50] = "The authentication type {0} is not supported. Check that you have configured the pg_hba.conf file to include the client''s IP address or subnet, and that it is using an authentication scheme supported by the driver.";
    t[51] = "Uwierzytelnienie typu {0} nie jest obsługiwane. Upewnij się, że skonfigurowałeś plik pg_hba.conf tak, że zawiera on adres IP lub podsieć klienta oraz że użyta metoda uwierzytelnienia jest wspierana przez ten sterownik.";
    t[52] = "Bad value for type {0} : {1}";
    t[53] = "Zła wartość dla typu {0}: {1}";
    t[54] = "This ResultSet is closed.";
    t[55] = "Ten ResultSet jest zamknięty.";
    t[60] = "Failed to create object for: {0}.";
    t[61] = "Nie powiodło się utworzenie obiektu dla: {0}.";
    t[62] = "Expected command status BEGIN, got {0}.";
    t[63] = "Spodziewano się statusu komendy BEGIN, otrzymano {0}.";
    t[64] = "The connection attempt failed.";
    t[65] = "Próba nawiązania połączenia nie powiodła się.";
    t[66] = "No results were returned by the query.";
    t[67] = "Zapytanie nie zwróciło żadnych wyników.";
    t[70] = "A CallableStatement was declared, but no call to registerOutParameter(1, <some type>) was made.";
    t[71] = "Funkcja CallableStatement została zadeklarowana, ale nie wywołano registerOutParameter (1, <jakiś typ>).";
    t[74] = "Premature end of input stream, expected {0} bytes, but only read {1}.";
    t[75] = "Przedwczesny koniec strumienia wejściowego, oczekiwano {0} bajtów, odczytano tylko {1}.";
    t[76] = "Something unusual has occurred to cause the driver to fail. Please report this exception.";
    t[77] = "Coś niezwykłego spowodowało pad sterownika. Proszę, zgłoś ten wyjątek.";
    t[78] = "Unknown type {0}.";
    t[79] = "Nieznany typ {0}.";
    t[84] = "Currently positioned before the start of the ResultSet.  You cannot call deleteRow() here.";
    t[85] = "Aktualna pozycja przed początkiem ResultSet. Nie można wywołać deleteRow().";
    t[86] = "Invalid character data was found.  This is most likely caused by stored data containing characters that are invalid for the character set the database was created in.  The most common example of this is storing 8bit data in a SQL_ASCII database.";
    t[87] = "Znaleziono nieprawidłowy znak. Najprawdopodobniej jest to spowodowane przechowywaniem w bazie znaków, które nie pasują do zestawu znaków wybranego podczas tworzenia bazy danych. Najczęstszy przykład to przechowywanie 8-bitowych znaków w bazie o kodowaniu SQL_ASCII.";
    t[90] = "Query timeout must be a value greater than or equals to 0.";
    t[91] = "Timeout zapytania musi być wartością dodatnią lub 0.";
    t[96] = "Unsupported Types value: {0}";
    t[97] = "Nieznana wartość Types: {0}";
    t[100] = "This PooledConnection has already been closed.";
    t[101] = "To PooledConnection zostało już zamknięte.";
    t[102] = "Protocol error.  Session setup failed.";
    t[103] = "Błąd protokołu. Nie udało się utworzyć sesji.";
    t[104] = "Server SQLState: {0}";
    t[105] = "Serwer SQLState: {0}";
    t[108] = "Cannot call cancelRowUpdates() when on the insert row.";
    t[109] = "Nie można wywołać cancelRowUpdates() na wstawianym rekordzie.";
    t[110] = "Where: {0}";
    t[111] = "Gdzie: {0}";
    t[112] = "The parameter index is out of range: {0}, number of parameters: {1}.";
    t[113] = "Indeks parametru jest poza zakresem: {0}, liczba parametrów: {1}.";
    t[114] = "A connection could not be made using the requested protocol {0}.";
    t[115] = "Nie można było nawiązać połączenia stosując żądany protokołu {0}.";
    t[116] = "Conversion to type {0} failed: {1}.";
    t[117] = "Konwersja do typu {0} nie powiodła się: {1}.";
    t[120] = "Error loading default settings from driverconfig.properties";
    t[121] = "Błąd podczas wczytywania ustawień domyślnych z driverconfig.properties";
    t[124] = "An error occurred while setting up the SSL connection.";
    t[125] = "Wystąpił błąd podczas ustanawiania połączenia SSL.";
    t[130] = "There are no rows in this ResultSet.";
    t[131] = "Nie ma żadnych wierszy w tym ResultSet.";
    t[132] = "Transaction isolation level {0} not supported.";
    t[133] = "Poziom izolacji transakcji {0} nie jest obsługiwany.";
    t[144] = "Cannot tell if path is open or closed: {0}.";
    t[145] = "Nie można stwierdzić, czy ścieżka jest otwarta czy zamknięta: {0}.";
    t[146] = "Currently positioned after the end of the ResultSet.  You cannot call deleteRow() here.";
    t[147] = "Aktualna pozycja za końcem ResultSet. Nie można wywołać deleteRow().";
    t[148] = "The maximum field size must be a value greater than or equal to 0.";
    t[149] = "Maksymalny rozmiar pola musi być wartością dodatnią lub 0.";
    t[150] = "Unexpected command status: {0}.";
    t[151] = "Nieoczekiwany status komendy: {0}.";
    t[158] = "Conversion of money failed.";
    t[159] = "Konwersja typu money nie powiodła się.";
    t[168] = "Zero bytes may not occur in string parameters.";
    t[169] = "Zerowe bajty nie mogą pojawiać się w parametrach typu łańcuch znakowy.";
    t[172] = "Fastpath call {0} - No result was returned and we expected an integer.";
    t[173] = "Wywołanie fastpath {0} - Nie otrzymano żadnego wyniku, a oczekiwano liczby całkowitej.";
    t[180] = "The fastpath function {0} is unknown.";
    t[181] = "Funkcja fastpath {0} jest nieznana.";
    t[184] = "Fetch size must be a value greater than or equal to 0.";
    t[185] = "Rozmiar pobierania musi być wartością dodatnią lub 0.";
    t[186] = "The array index is out of range: {0}";
    t[187] = "Indeks tablicy jest poza zakresem: {0}";
    t[190] = "DataSource has been closed.";
    t[191] = "DataSource zostało zamknięte.";
    t[196] = "Position: {0}";
    t[197] = "Pozycja: {0}";
    t[200] = "ResultSet is not updateable.  The query that generated this result set must select only one table, and must select all primary keys from that table. See the JDBC 2.1 API Specification, section 5.6 for more details.";
    t[201] = "ResultSet nie jest modyfikowalny (not updateable). Zapytanie, które zwróciło ten wynik musi dotyczyć tylko jednej tabeli oraz musi pobierać wszystkie klucze główne tej tabeli. Zobacz Specyfikację JDBC 2.1 API, rozdział 5.6, by uzyskać więcej szczegółów.";
    t[204] = "Method {0} is not yet implemented.";
    t[205] = "Metoda {0}nie jest jeszcze obsługiwana.";
    t[206] = "Too many update results were returned.";
    t[207] = "Zapytanie nie zwróciło żadnych wyników.";
    t[208] = "Cannot call deleteRow() when on the insert row.";
    t[209] = "Nie można wywołać deleteRow() na wstawianym rekordzie.";
    t[212] = "Cannot call updateRow() when on the insert row.";
    t[213] = "Nie można wywołać updateRow() na wstawianym rekordzie.";
    t[214] = "An unexpected result was returned by a query.";
    t[215] = "Zapytanie zwróciło nieoczekiwany wynik.";
    t[222] = "Internal Position: {0}";
    t[223] = "Wewnętrzna Pozycja: {0}";
    t[226] = "Conversion of interval failed";
    t[227] = "Konwersja typu interval nie powiodła się";
    t[232] = "A result was returned when none was expected.";
    t[233] = "Zwrócono wynik zapytania, choć nie był on oczekiwany.";
    t[234] = "The array index is out of range: {0}, number of elements: {1}.";
    t[235] = "Indeks tablicy jest poza zakresem: {0}, liczba elementów: {1}.";
    t[236] = "Not on the insert row.";
    t[237] = "Nie na wstawianym rekordzie.";
    table = t;
  }
  public java.lang.Object handleGetObject (java.lang.String msgid) throws java.util.MissingResourceException {
    int hash_val = msgid.hashCode() & 0x7fffffff;
    int idx = (hash_val % 121) << 1;
    {
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
    int incr = ((hash_val % 119) + 1) << 1;
    for (;;) {
      idx += incr;
      if (idx >= 242)
        idx -= 242;
      java.lang.Object found = table[idx];
      if (found == null)
        return null;
      if (msgid.equals(found))
        return table[idx + 1];
    }
  }
  public java.util.Enumeration getKeys () {
    return
      new java.util.Enumeration() {
        private int idx = 0;
        { while (idx < 242 && table[idx] == null) idx += 2; }
        public boolean hasMoreElements () {
          return (idx < 242);
        }
        public java.lang.Object nextElement () {
          java.lang.Object key = table[idx];
          do idx += 2; while (idx < 242 && table[idx] == null);
          return key;
        }
      };
  }
  public java.util.ResourceBundle getParent () {
    return parent;
  }
}
